import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — NoteRoute",
  description: "How NoteRoute collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground text-sm mb-10">
          Last updated: 22 February 2026
        </p>

        <Section title="1. Who We Are">
          <p>
            NoteRoute (&quot;NoteRoute&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) operates the NoteRoute
            web application (noteroute.click) and the NoteRoute mobile app for iOS and Android.
            Our infrastructure runs primarily on servers located in the United States (AWS
            us-east-1). For privacy enquiries, contact us at{" "}
            <a href="mailto:privacy@noteroute.click" className="underline">
              privacy@noteroute.click
            </a>
            .
          </p>
        </Section>

        <Section title="2. What Data We Collect">
          <SubSection title="2.1 Account Data">
            <ul className="list-disc pl-5 space-y-1">
              <li>Email address and display name (via Google Sign-In or email/password through Firebase Authentication).</li>
              <li>A unique user identifier generated by Firebase.</li>
            </ul>
          </SubSection>

          <SubSection title="2.2 Voice & Image Input">
            <ul className="list-disc pl-5 space-y-1">
              <li>
                Audio recordings you make are uploaded to Amazon S3 (us-east-1), processed for
                transcription, and then <strong>permanently deleted from S3</strong> once
                processing is complete.
              </li>
              <li>
                Images you capture or upload are handled the same way — uploaded, processed
                for text extraction or visual description, then deleted from S3.
              </li>
              <li>
                The <strong>transcript or extracted text</strong> is retained in your processing
                history (Routes) so you can review past notes. You can delete individual history
                entries from the app.
              </li>
            </ul>
          </SubSection>

          <SubSection title="2.3 Integration & Slot Data">
            <ul className="list-disc pl-5 space-y-1">
              <li>
                When you connect a third-party service (Notion, Google Docs/Drive, Slack,
                Todoist, Trello), we store the OAuth access token and, where applicable, refresh
                token for that service. All tokens are encrypted at rest using AES-256 (Fernet).
              </li>
              <li>
                We store the name, description, and a short content sample of each Knowledge
                Slot (destination page, document, or channel) you configure, so the AI can
                intelligently route your notes.
              </li>
              <li>
                Vector embeddings of your slot content are stored in a shared Pinecone index,
                partitioned strictly by your user ID. If you use Bring Your Own Integration
                (BYOI), they are stored in your private Pinecone index instead.
              </li>
            </ul>
          </SubSection>

          <SubSection title="2.4 Usage & Audit Data">
            <ul className="list-disc pl-5 space-y-1">
              <li>A log of each routing event (Route), including the transcript, summary, which slot was selected, and delivery status.</li>
              <li>Usage counters (number of routes per month, sources, slots) for tier enforcement.</li>
            </ul>
          </SubSection>

          <SubSection title="2.5 Bring Your Own LLM (BYOLLM) Keys">
            <p>
              If you supply your own OpenAI or Anthropic API key, we store it encrypted at rest
              and transmit it only to the respective provider to fulfil your requests. We do not
              log or retain the key value in plain text anywhere in our systems.
            </p>
          </SubSection>

          <SubSection title="2.6 Bring Your Own Integration (BYOI) Credentials">
            <p>
              If you connect your own Pinecone index or AWS Bedrock credentials, those
              credentials are stored encrypted at rest and used only to process your data.
              We never share or reuse them for any other purpose.
            </p>
          </SubSection>
        </Section>

        <Section title="3. How We Use Your Data">
          <ul className="list-disc pl-5 space-y-1">
            <li>To authenticate you and manage your account.</li>
            <li>To transcribe your voice notes and extract content from images.</li>
            <li>To embed your note content and search for the best-matching destination slot.</li>
            <li>To deliver your note to the third-party integration you have selected.</li>
            <li>To enforce tier limits and track your usage.</li>
            <li>To maintain a history of your routing events that you can review or delete.</li>
            <li>
              We do <strong>not</strong> use your data to train AI models, sell advertising, or
              share your information with third parties beyond what is necessary to operate the
              service (see Section 5).
            </li>
          </ul>
        </Section>

        <Section title="4. Legal Basis for Processing">
          <p>
            We rely on the following bases to process your personal data:
          </p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>
              <strong>Contract performance</strong> — processing your notes, managing integrations,
              and delivering content are necessary to provide the service you signed up for.
            </li>
            <li>
              <strong>Legitimate interests</strong> — maintaining security logs and enforcing
              usage limits.
            </li>
            <li>
              <strong>Consent</strong> — where you explicitly grant NoteRoute permission to access
              your third-party accounts (e.g. Google, Slack).
            </li>
          </ul>
        </Section>

        <Section title="5. Third-Party Services We Use">
          <p className="mb-3">
            To operate NoteRoute, your data passes through the following sub-processors:
          </p>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="border-b border-border">
                <th className="text-left py-2 pr-4 font-medium">Service</th>
                <th className="text-left py-2 pr-4 font-medium">Purpose</th>
                <th className="text-left py-2 font-medium">Location</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              <Row provider="Google Firebase" purpose="Authentication" location="USA" />
              <Row provider="Amazon Web Services (S3, Bedrock)" purpose="Temporary audio/image storage; AI embedding" location="USA (us-east-1)" />
              <Row provider="Groq" purpose="Speech-to-text transcription" location="USA" />
              <Row provider="Pinecone" purpose="Vector search" location="USA" />
              <Row provider="MongoDB Atlas" purpose="Database (user data, routes, integrations)" location="USA" />
              <Row provider="Railway" purpose="Application hosting" location="USA" />
              <Row provider="Notion / Google / Slack / Todoist / Trello" purpose="Destination integrations (only accessed when you connect them)" location="Varies" />
              <Row provider="OpenAI (BYOLLM only)" purpose="AI text generation using your own API key" location="USA" />
              <Row provider="Anthropic (BYOLLM only)" purpose="AI text generation using your own API key" location="USA" />
            </tbody>
          </table>
          <p className="mt-3 text-muted-foreground text-sm">
            Each sub-processor is contractually bound to protect your data and process it only
            as instructed.
          </p>
        </Section>

        <Section title="6. Data Retention">
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>Audio & images:</strong> Deleted from S3 immediately after processing
              (typically within seconds).
            </li>
            <li>
              <strong>Transcripts & route history:</strong> Retained until you delete them or
              close your account.
            </li>
            <li>
              <strong>Integration tokens:</strong> Retained until you disconnect the integration
              or close your account, at which point they are permanently deleted.
            </li>
            <li>
              <strong>Vector embeddings:</strong> Retained in Pinecone until you delete the
              associated slot or close your account.
            </li>
            <li>
              <strong>Account data:</strong> Retained for 30 days after account deletion to
              allow recovery, then permanently purged.
            </li>
          </ul>
        </Section>

        <Section title="7. Your Rights">
          <p className="mb-2">You have the right to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Access</strong> the personal data we hold about you.</li>
            <li><strong>Correct</strong> inaccurate data.</li>
            <li><strong>Delete</strong> your account and associated data at any time from the app settings.</li>
            <li><strong>Export</strong> your routing history (contact us to request a data export).</li>
            <li><strong>Withdraw consent</strong> for any integration by disconnecting it — this immediately revokes our access to that provider on your behalf.</li>
            <li><strong>Object</strong> to processing based on legitimate interests.</li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, email{" "}
            <a href="mailto:privacy@noteroute.click" className="underline">
              privacy@noteroute.click
            </a>
            . We will respond within 30 days.
          </p>
        </Section>

        <Section title="8. Security">
          <ul className="list-disc pl-5 space-y-1">
            <li>All data in transit is encrypted via TLS 1.2+.</li>
            <li>OAuth tokens and API keys are encrypted at rest using AES-256 (Fernet).</li>
            <li>Vector embeddings are partitioned by user ID — no user can access another user&apos;s data.</li>
            <li>Firebase ID tokens are verified server-side on every authenticated request.</li>
            <li>Audio and image files are stored in a private S3 bucket accessible only via short-lived pre-signed URLs.</li>
          </ul>
        </Section>

        <Section title="9. Children's Privacy">
          <p>
            NoteRoute is not directed at children under the age of 13 (or 16 where required by
            applicable law). We do not knowingly collect personal data from children. If you
            believe a child has provided us with personal data, contact us and we will delete it
            promptly.
          </p>
        </Section>

        <Section title="10. International Data Transfers">
          <p>
            NoteRoute is operated from Ghana. Your data is processed on servers in the United
            States. By using the service, you acknowledge that your data will be transferred to
            and processed in the United States, which may have different data protection laws
            than your country of residence. We take reasonable steps to ensure your data
            receives an adequate level of protection wherever it is processed.
          </p>
        </Section>

        <Section title="11. Cookies & Analytics">
          <p>
            The web app uses only essential session cookies required for authentication. We do
            not use third-party analytics trackers or advertising cookies. The mobile app does
            not use cookies.
          </p>
        </Section>

        <Section title="12. Changes to This Policy">
          <p>
            We may update this policy from time to time. We will notify you of material changes
            by email or via an in-app notice at least 14 days before they take effect. Continued
            use of NoteRoute after the effective date constitutes acceptance of the updated policy.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>
            For privacy-related questions or requests, contact us at{" "}
            <a href="mailto:privacy@noteroute.click" className="underline">
              privacy@noteroute.click
            </a>
            .
          </p>
        </Section>

        <p className="mt-16 text-xs text-muted-foreground">
          &copy; {new Date().getFullYear()} NoteRoute. All rights reserved.
        </p>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold mb-3">{title}</h2>
      <div className="text-muted-foreground space-y-2 leading-relaxed">{children}</div>
    </section>
  );
}

function SubSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mb-4">
      <h3 className="font-medium text-foreground mb-1">{title}</h3>
      {children}
    </div>
  );
}

function Row({
  provider,
  purpose,
  location,
}: {
  provider: string;
  purpose: string;
  location: string;
}) {
  return (
    <tr>
      <td className="py-2 pr-4 font-medium text-foreground">{provider}</td>
      <td className="py-2 pr-4">{purpose}</td>
      <td className="py-2">{location}</td>
    </tr>
  );
}
